// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/v1/ArticleManagementService.proto

package v1

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Article struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               int64                `protobuf:"varint,3,opt,name=author,proto3" json:"author,omitempty"`
	Category             int64                `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fdc0ca575f6b, []int{0}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Article) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Article) GetAuthor() int64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *Article) GetCategory() int64 {
	if m != nil {
		return m.Category
	}
	return 0
}

func (m *Article) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type ArtRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   int64    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtRequest) Reset()         { *m = ArtRequest{} }
func (m *ArtRequest) String() string { return proto.CompactTextString(m) }
func (*ArtRequest) ProtoMessage()    {}
func (*ArtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fdc0ca575f6b, []int{1}
}

func (m *ArtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtRequest.Unmarshal(m, b)
}
func (m *ArtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtRequest.Marshal(b, m, deterministic)
}
func (m *ArtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtRequest.Merge(m, src)
}
func (m *ArtRequest) XXX_Size() int {
	return xxx_messageInfo_ArtRequest.Size(m)
}
func (m *ArtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ArtRequest proto.InternalMessageInfo

func (m *ArtRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ArtRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ArtRespones struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Article              *Article `protobuf:"bytes,2,opt,name=article,proto3" json:"article,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArtRespones) Reset()         { *m = ArtRespones{} }
func (m *ArtRespones) String() string { return proto.CompactTextString(m) }
func (*ArtRespones) ProtoMessage()    {}
func (*ArtRespones) Descriptor() ([]byte, []int) {
	return fileDescriptor_1905fdc0ca575f6b, []int{2}
}

func (m *ArtRespones) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtRespones.Unmarshal(m, b)
}
func (m *ArtRespones) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtRespones.Marshal(b, m, deterministic)
}
func (m *ArtRespones) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtRespones.Merge(m, src)
}
func (m *ArtRespones) XXX_Size() int {
	return xxx_messageInfo_ArtRespones.Size(m)
}
func (m *ArtRespones) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtRespones.DiscardUnknown(m)
}

var xxx_messageInfo_ArtRespones proto.InternalMessageInfo

func (m *ArtRespones) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ArtRespones) GetArticle() *Article {
	if m != nil {
		return m.Article
	}
	return nil
}

func init() {
	proto.RegisterType((*Article)(nil), "v1.Article")
	proto.RegisterType((*ArtRequest)(nil), "v1.ArtRequest")
	proto.RegisterType((*ArtRespones)(nil), "v1.ArtRespones")
}

func init() {
	proto.RegisterFile("api/proto/v1/ArticleManagementService.proto", fileDescriptor_1905fdc0ca575f6b)
}

var fileDescriptor_1905fdc0ca575f6b = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x86, 0x49, 0x7a, 0xdb, 0xde, 0x9e, 0x5c, 0xda, 0xcb, 0x70, 0xaf, 0x86, 0xa0, 0x58, 0x02,
	0x42, 0x41, 0x48, 0x68, 0x5d, 0xbb, 0xe8, 0x46, 0x70, 0xe1, 0xc2, 0xa8, 0x6b, 0x99, 0x36, 0xa7,
	0x71, 0x20, 0xc9, 0xc4, 0xc9, 0x49, 0x40, 0xc4, 0x8d, 0xaf, 0xe0, 0x1b, 0xf8, 0x4a, 0xbe, 0x82,
	0x0f, 0x22, 0x9d, 0x99, 0x14, 0x17, 0xba, 0xcb, 0xcf, 0xff, 0xff, 0x27, 0xdf, 0x9c, 0x03, 0x27,
	0xbc, 0x12, 0x71, 0xa5, 0x24, 0xc9, 0xb8, 0x9d, 0xc7, 0x4b, 0x45, 0x62, 0x9d, 0xe3, 0x25, 0x2f,
	0x79, 0x86, 0x05, 0x96, 0x74, 0x8d, 0xaa, 0x15, 0x6b, 0x8c, 0x74, 0x82, 0xb9, 0xed, 0x3c, 0x38,
	0xca, 0xa4, 0xcc, 0x72, 0x34, 0x9d, 0x55, 0xb3, 0x89, 0x49, 0x14, 0x58, 0x13, 0x2f, 0x2a, 0x13,
	0x0a, 0x0e, 0x6c, 0x60, 0x3b, 0x98, 0x97, 0xa5, 0x24, 0x4e, 0x42, 0x96, 0xb5, 0x71, 0xc3, 0x37,
	0x07, 0x86, 0xf6, 0x2f, 0x6c, 0x0c, 0xae, 0x48, 0x7d, 0x67, 0xea, 0xcc, 0x7a, 0x89, 0x2b, 0x52,
	0xf6, 0x0f, 0xfa, 0x24, 0x28, 0x47, 0xdf, 0x9d, 0x3a, 0xb3, 0x51, 0x62, 0x04, 0xdb, 0x83, 0x01,
	0x6f, 0xe8, 0x5e, 0x2a, 0xbf, 0xa7, 0x93, 0x56, 0xb1, 0x00, 0x7e, 0xaf, 0x39, 0x61, 0x26, 0xd5,
	0xa3, 0xff, 0x4b, 0x3b, 0x3b, 0xcd, 0xce, 0xe0, 0x4f, 0xce, 0x6b, 0xba, 0x6b, 0xaa, 0x94, 0x13,
	0xa6, 0x7e, 0x7f, 0xea, 0xcc, 0xbc, 0x45, 0x10, 0x19, 0xb4, 0xa8, 0x63, 0x8f, 0x6e, 0x3a, 0xf6,
	0xc4, 0xdb, 0xe6, 0x6f, 0x4d, 0x3c, 0x8c, 0x00, 0x96, 0x8a, 0x12, 0x7c, 0x68, 0xb0, 0x26, 0xf6,
	0x17, 0x7a, 0xbc, 0x12, 0x9a, 0x73, 0x94, 0x6c, 0x3f, 0x2d, 0xb8, 0xdb, 0x81, 0x87, 0xe7, 0xe0,
	0xe9, 0x7c, 0x5d, 0xc9, 0x12, 0xeb, 0x6f, 0x0a, 0xc7, 0x30, 0xe4, 0xe6, 0xd1, 0xba, 0xe5, 0x2d,
	0xbc, 0xa8, 0x9d, 0x47, 0x76, 0x0f, 0x49, 0xe7, 0x2d, 0x0a, 0xf0, 0x7f, 0xba, 0x00, 0xbb, 0x82,
	0x49, 0x86, 0x64, 0xed, 0x8b, 0x72, 0x23, 0x15, 0x1b, 0xdb, 0x21, 0x16, 0x34, 0x98, 0xec, 0xb4,
	0x01, 0x09, 0x0f, 0x5f, 0xde, 0x3f, 0x5e, 0xdd, 0xfd, 0xf0, 0xff, 0x97, 0xdb, 0xea, 0x6a, 0xfc,
	0x24, 0xd2, 0xe7, 0xd5, 0x40, 0xef, 0xe1, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x2c, 0xac,
	0x3e, 0x04, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticleManagementServiceClient is the client API for ArticleManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleManagementServiceClient interface {
	GetArticleInfor(ctx context.Context, in *ArtRequest, opts ...grpc.CallOption) (*ArtRespones, error)
}

type articleManagementServiceClient struct {
	cc *grpc.ClientConn
}

func NewArticleManagementServiceClient(cc *grpc.ClientConn) ArticleManagementServiceClient {
	return &articleManagementServiceClient{cc}
}

func (c *articleManagementServiceClient) GetArticleInfor(ctx context.Context, in *ArtRequest, opts ...grpc.CallOption) (*ArtRespones, error) {
	out := new(ArtRespones)
	err := c.cc.Invoke(ctx, "/v1.ArticleManagementService/getArticleInfor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleManagementServiceServer is the server API for ArticleManagementService service.
type ArticleManagementServiceServer interface {
	GetArticleInfor(context.Context, *ArtRequest) (*ArtRespones, error)
}

func RegisterArticleManagementServiceServer(s *grpc.Server, srv ArticleManagementServiceServer) {
	s.RegisterService(&_ArticleManagementService_serviceDesc, srv)
}

func _ArticleManagementService_GetArticleInfor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArtRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleManagementServiceServer).GetArticleInfor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ArticleManagementService/GetArticleInfor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleManagementServiceServer).GetArticleInfor(ctx, req.(*ArtRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArticleManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ArticleManagementService",
	HandlerType: (*ArticleManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getArticleInfor",
			Handler:    _ArticleManagementService_GetArticleInfor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/v1/ArticleManagementService.proto",
}
