server:
  port: 8020

<<<<<<< HEAD
service:
  defaultMinMs: 100
  defaultMaxMs: 20

=======
>>>>>>> 1badb4e2d4fd7770aa200a15a31b7657a79f77a7
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

service:
  defaultMinMs: 100
  defaultMaxMs: 20