info:
  component: Zuul Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
<<<<<<< HEAD
    product:
      path: /product/**
      url: http://192.168.1.6:8080/product
#      stripPrefix: false
    review:
      path: /review/**
      service-id: review
#      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
=======
    productcomposite:
      path: /productcomposite/**
#      stripPrefix: false
>>>>>>> 1badb4e2d4fd7770aa200a15a31b7657a79f77a7

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO