info:
  component: Config Server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8060

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhakui/config.git
          search-paths: ./
      label: master

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO