version: "3"
services:

  edgeservice:
    build: ./edge-service
    ports:
      - "8765:8765"
    expose:
      - 8761
    networks:
      - default

  productservice:
    build: ../core/product-service
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - default
  
  recommendationservice:
    build: ../core/recommendation-service
    ports:
      - "8010:8010"
    expose:
      - 8010
    networks:
      - default
  
  reviewservice:
    build: ../core/review-service
    ports:
      - "8020:8020"
    expose:
      - 8020
    networks:
      - default
  
  productcomposite:
    build: ../composite/productcomposite
    ports:
      - "8030:8030"
    expose:
      - 8030
    networks:
      - default

networks:
  default:
    external:
      name: my-net